name: cd-pipeline
on:
    workflow_run: 
        workflows: 
            - "ci-pipeline"
        types: 
            - completed
jobs:
    cd-job:
        runs-on: ubuntu-latest
        #Job will only run if the Dependecy Workflow 
        if: ${{github.event.workflow_run.conclusion=='success'}}
        steps:
            - name: Help Needed
              run: echo "Allah Please Help Me"
            - name: check Previous Workflow Run Status
              run: echo "${{github.event.workflow_run.conclusion=='success'}}"         
            - name: Checking Dependency Workflow
              run: echo "${{github.event.workflow.name}}"  
            - name: Checkout Repository
              uses: actions/checkout@v4
              # now set up parcel to build the website
            - name: Setup Parcel Tool to Build the website
              run: npm install --save-dev parcel
            - name: check the contents of Package.json
              run: cat package.json
            - name: List Contents of WD
              run: ls -a
            - name: Build the Website
              run: npx parcel build "${{github.workspace}}/index.html"
            - name: Check The Contents of the WD after the Build Operation
              run: ls -a
            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./dist
            # End of Workflow
              