name: ci-pipeline
on: 
  push:
    branches:
    -  "**"
jobs:
  linting-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      # following step is just for testing
      - name: Check WD
        run: | 
          echo ${{github.workspace}}
          echo ${{github.action_repository}} 
          echo ${{github.action_ref}}
          echo ${{github.event_name}}
          echo ${{github.actor}}
      - name: Install HTML Hint
        run: npm install --save-dev htmlhint
      - name: Install Styleline
        run: npm install --save-dev stylelint stylelint-config-standard
      - name: Checking File Listing and Package.json Contents
        run: |
          echo "--- File Contents ----"
          ls -a
          echo "--- Package.json Contents ---"
          cat package.json
      - name: Lint HTML
        run: npx htmlhint **/*.html
      - name: Lint CSS Files
        run: npx stylelint **/*.css