name: ci-pipeline
on: 
  push:
    branches:
    -  "**"
jobs:
  linting-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      # following step is just for testing
      - name: Check WD
        run: | 
          echo ${{github.workspace}}
          echo ${{github.action_repository}} 
          echo ${{github.action_ref}}
          echo ${{github.event_name}}
          echo ${{github.actor}}